fail_fast: true


repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=121]
        files: ^rvt/

  - repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
        files: ^rvt/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        verbose: true
        entry: bash -c 'mypy "$@" || true' --
        args: [--strict]
        files: ^rvt/
