fail_fast: true


repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: python dev_tools/black_formatting.py
      language: system
      types: [ python ]
      verbose: true
    - id: pylint
      name: pylint
      entry: python dev_tools/pylint_check.py
      language: system
      types: [ python ]
      verbose: true
    - id: mypy
      name: mypy
      entry: python dev_tools/mypy_check.py
      language: system
      types: [ python ]
      verbose: true
