{% set name = "rvt_py" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 604c26cb5e09682be51ebd72c60d54a06d4cdd0a478c6ec3587483a5c71a5b2e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - gdal
    - matplotlib
    - numpy
    - pip
    - python
    - scipy
  run:
    - gdal
    - matplotlib
    - numpy
    - python
    - scipy

test:
  imports:
    - rvt

about:
  home: https://github.com/EarthObservation/RVT_py
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: Relief Visualization Toolbox python library. It helps scientist visualize raster elevation model datasets.
  doc_url: https://rvt-py.readthedocs.io/en/latest/
  dev_url: 

extra:
  recipe-maintainers:
    - zmigyyy
