{% set name = "rvt_py" %}
{% set version = "1.0.0a7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad224563e46bbfa745e1197c64e59e8e4e0951e462f8e8d9474370f655953d0e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - gdal
    - matplotlib
    - numpy
    - pip
    - python
    - scipy
  run:
    - gdal
    - matplotlib
    - numpy
    - python
    - scipy

test:
  imports:
    - rvt

about:
  home: https://github.com/EarthObservation/RVT_py
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: Relief Visualization Toolbox python library. It helps scientist visualize raster elevation model datasets.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
