{% set name = "rvt_py" %}
{% set version = "1.0.0a8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e4b521ab953ac8126d8b54fc11c4394c2d4488008ec93d99285e12100d2ab78

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - gdal
    - matplotlib
    - numpy
    - pip
    - python
    - scipy
  run:
    - gdal
    - matplotlib
    - numpy
    - python
    - scipy

test:
  imports:
    - rvt

about:
  home: https://github.com/EarthObservation/RVT_py
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: Relief Visualization Toolbox python library. It helps scientist visualize raster elevation model datasets.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
