{% set name = "rvt_py" %}
{% set version = "2.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21089afb9bb22fd88d4cd8a7a32e7ddb23632d455e5759400ef9fd920d40245a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
    - gdal
  run:
    - python
    - gdal
    - numpy >=1.23,<=2.2.3
    - scipy
    - matplotlib
    - pandas
    - geopandas
    - rasterio
    - jupyter

test:
  imports:
    - rvt

about:
  home: https://github.com/EarthObservation/RVT_py
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Relief Visualization Toolbox python library. It helps scientist visualize raster elevation model datasets.
  doc_url: https://rvt-py.readthedocs.io/en/latest/
  dev_url: https://github.com/EarthObservation/RVT_py

extra:
  recipe-maintainers:
    - zmigyyy
    - NejcCoz # Github ID
